[package]
name = "kyler-bracken/suit-up-test"
version = "2.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.4"
Component = "sleitnick/component@2.4.4"
Trove = "sleitnick/trove@0.3.0"
Timer = "sleitnick/timer@1.1.1"
Signal = "sleitnick/signal@1.1.0"
Comm = "sleitnick/comm@0.3.1"
Roact = "roblox/roact@1.4.4"