[package]
name = "kyler-bracken/suit-up-test"
version = "2.0.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.4"
Component = "sleitnick/component@2.4.4"
Trove = "sleitnick/trove@0.3.0"
Timer = "sleitnick/timer@1.1.1"
Signal = "sleitnick/signal@1.1.0"
Option = "sleitnick/option@1.0.3"
Shake = "sleitnick/shake@0.1.4"
Comm = "sleitnick/comm@0.3.1"
Roact = "roblox/roact@1.4.4"
RoactRodux = "roblox/roact-rodux@0.5.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
TableUtil = "sleitnick/table-util@1.1.1"
EnumList = "sleitnick/enum-list@2.0.0"
Flipper = "reselim/flipper@^2"
RoactFlipper = "reselim/roact-flipper@^1"
Input = "sleitnick/input@1.3.2"
Hooks = "kampfkarren/roact-hooks@^0"
Promise = "evaera/promise@^4"
PID = "sleitnick/pid@1.0.1"
Datastore2 = "nidoxs/datastore2@1.4.0"
Sift = "csqrl/sift@0.0.3"